services:
  server:
    build:
      context: .
    ports:
      - 9000:80
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    environment:
      - PASSWORD_FILE_PATH=/run/secrets/db-password
      - DB_HOST=db
      - DB_NAME=lgbtfriendsdb
      - DB_USER=root
    volumes:
      - './src/css/min:/var/www/html/css/min:rw'
      - './src/js/min:/var/www/html/js/min:rw'
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html
  db:
    image: mariadb
    restart: always
    user: root
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MARIADB_DATABASE=lgbtfriendsdb
    ports:
      - 9001:3306
    healthcheck:
      test:  ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect",  "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db
  node:
    build:
      context: .
      target: node-builder
    working_dir: /app
    volumes:
      - './src/css/min:/app/css/min:rw'
      - './src/js/min:/app/js/min:rw'
    develop:
      watch:
        - action: sync
          path: ./src/css
          target: /app/css
        - action: sync
          path: ./src/js
          target: /app/js
    environment:
      - SHELL=/bin/sh
    command: ["/bin/sh", "-c", "ls -la && /app/node_sh/node_start.sh"]
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt