<?php
require_once(dirname(__DIR__) . '/util/validate.php'); // include database connection file

function template_footer(array $scripts = null): void
{
    // ------------------- LOGIN CHECK -------------------
    $loggedIn = false;

    if (isset($_SESSION['loggedin']) && $_SESSION['loggedin'] === true) {
        $loggedIn = true;
    }
    // ----------------- LOGIN CHECK END -------------------

    // add loading_spinner.js to scripts array
    //$scripts[] = 'loading_spinner.js';

    // add authorization window script to scripts array
    $scripts[] = 'auth_window.js';

    echo <<<EOT
    <!-- Generated by template_footer -->
    </main>
    <footer>
        <nav class="nav-bottom navbar">
        </nav>
    </footer>
</div>
EOT;
    if ($scripts !== null) {
        foreach ($scripts as $script) {
            echo '<script src="./js/' . $script . '"></script>';
        }
    }
    echo <<<EOT
</body>
</html>
EOT;
    getErrorMsg();
}